services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    build: .
    restart: always
    environment:
      - DEBUG=False
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  celery:
    build: .
    restart: always
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: