services:
  # Return it maybe in undefined future
  #django:
  #  profiles:
  #    - deploy
  #  build: .
  #  image: python:3.11-slim-buster
  #  command: >
  #    sh -c "python manage.py loaddata ./fixtures/sources.json
  #           python manage.py runserver 0.0.0.0:8000"
  #  volumes:
  #    - ./:/usr/src/app/
  #  ports:
  #    - 8000:8000
  #  env_file:
  #    - ./.env
  #  depends_on:
  #    - mongodb
  #  networks:
  #    - app-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=ankizator
    volumes:
      - ./.db_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge