services:
  db:
    extends:
      file: docker/base.yaml
      service: db-base
    ports:
      - "5432:5432"
  web:
    ports:
      - "8000:8000"
    profiles:
      - ""
    extends:
      file: docker/base.yaml
      service: web-base
    develop:
      watch:
        - action: sync
          path: .
          target: /app/

  web-test:
    ports:
      - "8000:8000"
    command: "python manage.py test"
    profiles:
      - "test"
    extends:
      file: docker/base.yaml
      service: web-base
    environment:
      - RUN_HEAVY_TESTS=${RUN_HEAVY_TESTS-False}
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app/

volumes:
  postgres_data:
