services:
  db:
    image: postgres:17
    restart: always
    extends:
      file: docker/base.yaml
      service: db-base

  redis:
    image: redis:7
    restart: always

  web:
    build: .
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    environment:
      DEBUG: False
      RUN_MIGRATIONS: ${RUN_MIGRATIONS-true}
    depends_on:
      - redis
      - db
    extends:
      file: docker/base.yaml
      service: web-base

  celery:
    build: .
    command: celery -A config worker -l info
    restart: always
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  postgres_data:
  static_volume:
  media_volume: