###

POST http://localhost:8000/api/words
Content-Type: application/json

{ "source" : "https://merula.pl/jezyk-angielski/repetytorium-jednotomowe-pr-rozdzial-1-czlowiek-tabela-slow/" }

###

POST http://localhost:8000/api/contexts
Content-Type: application/json

{
  "words": [{
      "pl": "dredy",
      "en": "dreadlocks"
    }]
}

###