# Generated by Django 5.1.4 on 2024-12-14 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_word_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
