# Generated by Django 5.1.4 on 2024-12-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_source_collection_rename_pl_context_og_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.collection'),
            preserve_default=False,
        ),
    ]
